add_repeat_lesson_2
mrDonald009/GeekUniversity pull request #1
Opened 2020-12-08 15:56 UTC by mrDonald009

2020-12-09 08:25 UTC, mrDonald009 commented
не могу разобраться, почему не выводит наименование и цену товаров...

2020-12-09 12:59 UTC, Vokler requested changes

2020-12-09 12:59 UTC, Vokler commented on 6. основы_django_framework/lesson_2/geekshop/mainapp/templates/mainapp/base.html
> +{% load static %}
Обратите внимание, что тут должен быть не static, а staticfiles

2020-12-09 12:59 UTC, Vokler commented on 6. основы_django_framework/lesson_2/geekshop/mainapp/templates/mainapp/index.html
> +{% load static %}
Тут то же самое что выше указал

2020-12-09 12:59 UTC, Vokler commented on 6. основы_django_framework/lesson_2/geekshop/mainapp/templates/mainapp/products.html
> +{% load static %}
И тут

2020-12-10 09:07 UTC, mrDonald009 commented on 6. основы_django_framework/lesson_2/geekshop/mainapp/templates/mainapp/base.html
> +{% load static %}
Валерий объясните пожалуйста, в чем разница, информация от этого на страницах не меняется и на уроке мы разбирали, что наследование идет от static

2020-12-13 12:24 UTC, merged